=== QuiWorks/golf-league/src/test/resources/legacy/schema/Holes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="HolesList">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Holes" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Holes">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="CourseId NineName HoleNo " primary="yes" unique="yes" clustered="no" order="asc asc asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="CourseId" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="NineName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="HoleNo" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Hdcp" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Par" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Yardage" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== QuiWorks/golf-league/src/test/resources/legacy/data/Holes.xml
<?xml version="1.0" encoding="UTF-8"?>
<HolesList xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Holes.xsd" generated="2021-06-05T13:50:09">
<Holes>
<CourseId>1</CourseId>
<NineName>Back</NineName>
<HoleNo>10</HoleNo>
<Hdcp>4</Hdcp>
<Par>5</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Back</NineName>
<HoleNo>11</HoleNo>
<Hdcp>10</Hdcp>
<Par>3</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Back</NineName>
<HoleNo>12</HoleNo>
<Hdcp>12</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Back</NineName>
<HoleNo>13</HoleNo>
<Hdcp>16</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Back</NineName>
<HoleNo>14</HoleNo>
<Hdcp>8</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Back</NineName>
<HoleNo>15</HoleNo>
<Hdcp>18</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Back</NineName>
<HoleNo>16</HoleNo>
<Hdcp>6</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Back</NineName>
<HoleNo>17</HoleNo>
<Hdcp>14</Hdcp>
<Par>3</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Back</NineName>
<HoleNo>18</HoleNo>
<Hdcp>2</Hdcp>
<Par>5</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Front</NineName>
<HoleNo>1</HoleNo>
<Hdcp>7</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Front</NineName>
<HoleNo>2</HoleNo>
<Hdcp>1</Hdcp>
<Par>5</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Front</NineName>
<HoleNo>3</HoleNo>
<Hdcp>13</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Front</NineName>
<HoleNo>4</HoleNo>
<Hdcp>15</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Front</NineName>
<HoleNo>5</HoleNo>
<Hdcp>17</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Front</NineName>
<HoleNo>6</HoleNo>
<Hdcp>11</Hdcp>
<Par>3</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Front</NineName>
<HoleNo>7</HoleNo>
<Hdcp>5</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Front</NineName>
<HoleNo>8</HoleNo>
<Hdcp>3</Hdcp>
<Par>3</Par>
</Holes>
<Holes>
<CourseId>1</CourseId>
<NineName>Front</NineName>
<HoleNo>9</HoleNo>
<Hdcp>9</Hdcp>
<Par>5</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Back</NineName>
<HoleNo>10</HoleNo>
<Hdcp>6</Hdcp>
<Par>5</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Back</NineName>
<HoleNo>11</HoleNo>
<Hdcp>10</Hdcp>
<Par>3</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Back</NineName>
<HoleNo>12</HoleNo>
<Hdcp>12</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Back</NineName>
<HoleNo>13</HoleNo>
<Hdcp>18</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Back</NineName>
<HoleNo>14</HoleNo>
<Hdcp>4</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Back</NineName>
<HoleNo>15</HoleNo>
<Hdcp>16</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Back</NineName>
<HoleNo>16</HoleNo>
<Hdcp>8</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Back</NineName>
<HoleNo>17</HoleNo>
<Hdcp>14</Hdcp>
<Par>3</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Back</NineName>
<HoleNo>18</HoleNo>
<Hdcp>2</Hdcp>
<Par>5</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Front</NineName>
<HoleNo>1</HoleNo>
<Hdcp>11</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Front</NineName>
<HoleNo>2</HoleNo>
<Hdcp>7</Hdcp>
<Par>5</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Front</NineName>
<HoleNo>3</HoleNo>
<Hdcp>5</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Front</NineName>
<HoleNo>4</HoleNo>
<Hdcp>17</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Front</NineName>
<HoleNo>5</HoleNo>
<Hdcp>15</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Front</NineName>
<HoleNo>6</HoleNo>
<Hdcp>13</Hdcp>
<Par>3</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Front</NineName>
<HoleNo>7</HoleNo>
<Hdcp>1</Hdcp>
<Par>4</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Front</NineName>
<HoleNo>8</HoleNo>
<Hdcp>3</Hdcp>
<Par>3</Par>
</Holes>
<Holes>
<CourseId>2</CourseId>
<NineName>Front</NineName>
<HoleNo>9</HoleNo>
<Hdcp>9</Hdcp>
<Par>5</Par>
</Holes>
</HolesList>
