=== QuiWorks/golf-league/src/test/resources/legacy/schema/ScheduleMaster.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="ScheduleMasterList">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="ScheduleMaster" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="ScheduleMaster">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Flight" index-key="Flight " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="Ctr " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="Week" index-key="Week " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="qurPNnrz3Ue/cB5cBYF8Vg==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Ctr" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Week" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Flight" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Home1" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Away1" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Home2" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Away2" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Home3" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Away3" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Home4" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Away4" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Home5" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Away5" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Home6" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Away6" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Home7" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Away7" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Home8" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Away8" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Home9" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Away9" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Back9" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== QuiWorks/golf-league/src/test/resources/legacy/data/ScheduleMaster.xml
<?xml version="1.0" encoding="UTF-8"?>
<ScheduleMasterList xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="ScheduleMaster.xsd" generated="2021-06-05T13:52:13">
<ScheduleMaster>
<Ctr>1654</Ctr>
<Week>1</Week>
<Flight>1</Flight>
<Home1>0</Home1>
<Away1>0</Away1>
<Home2>0</Home2>
<Away2>0</Away2>
<Home3>0</Home3>
<Away3>0</Away3>
<Home4>0</Home4>
<Away4>0</Away4>
<Home5>0</Home5>
<Away5>0</Away5>
<Home6>0</Home6>
<Away6>0</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>1</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1655</Ctr>
<Week>2</Week>
<Flight>1</Flight>
<Home1>1</Home1>
<Away1>9</Away1>
<Home2>4</Home2>
<Away2>8</Away2>
<Home3>3</Home3>
<Away3>10</Away3>
<Home4>5</Home4>
<Away4>11</Away4>
<Home5>2</Home5>
<Away5>12</Away5>
<Home6>6</Home6>
<Away6>7</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>0</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1656</Ctr>
<Week>3</Week>
<Flight>1</Flight>
<Home1>2</Home1>
<Away1>3</Away1>
<Home2>6</Home2>
<Away2>12</Away2>
<Home3>5</Home3>
<Away3>9</Away3>
<Home4>1</Home4>
<Away4>10</Away4>
<Home5>8</Home5>
<Away5>11</Away5>
<Home6>4</Home6>
<Away6>7</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>1</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1657</Ctr>
<Week>4</Week>
<Flight>1</Flight>
<Home1>11</Home1>
<Away1>12</Away1>
<Home2>3</Home2>
<Away2>4</Away2>
<Home3>5</Home3>
<Away3>6</Away3>
<Home4>7</Home4>
<Away4>8</Away4>
<Home5>9</Home5>
<Away5>10</Away5>
<Home6>1</Home6>
<Away6>2</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>0</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1658</Ctr>
<Week>5</Week>
<Flight>1</Flight>
<Home1>0</Home1>
<Away1>0</Away1>
<Home2>0</Home2>
<Away2>0</Away2>
<Home3>0</Home3>
<Away3>0</Away3>
<Home4>0</Home4>
<Away4>0</Away4>
<Home5>0</Home5>
<Away5>0</Away5>
<Home6>0</Home6>
<Away6>0</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>1</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1659</Ctr>
<Week>6</Week>
<Flight>1</Flight>
<Home1>2</Home1>
<Away1>7</Away1>
<Home2>9</Home2>
<Away2>12</Away2>
<Home3>1</Home3>
<Away3>8</Away3>
<Home4>3</Home4>
<Away4>11</Away4>
<Home5>4</Home5>
<Away5>6</Away5>
<Home6>5</Home6>
<Away6>10</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>1</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1660</Ctr>
<Week>7</Week>
<Flight>1</Flight>
<Home1>4</Home1>
<Away1>5</Away1>
<Home2>2</Home2>
<Away2>10</Away2>
<Home3>7</Home3>
<Away3>11</Away3>
<Home4>6</Home4>
<Away4>9</Away4>
<Home5>1</Home5>
<Away5>12</Away5>
<Home6>3</Home6>
<Away6>8</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>0</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1661</Ctr>
<Week>8</Week>
<Flight>1</Flight>
<Home1>5</Home1>
<Away1>12</Away1>
<Home2>1</Home2>
<Away2>7</Away2>
<Home3>3</Home3>
<Away3>9</Away3>
<Home4>2</Home4>
<Away4>8</Away4>
<Home5>6</Home5>
<Away5>11</Away5>
<Home6>4</Home6>
<Away6>10</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>1</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1662</Ctr>
<Week>9</Week>
<Flight>1</Flight>
<Home1>0</Home1>
<Away1>0</Away1>
<Home2>0</Home2>
<Away2>0</Away2>
<Home3>0</Home3>
<Away3>0</Away3>
<Home4>0</Home4>
<Away4>0</Away4>
<Home5>0</Home5>
<Away5>0</Away5>
<Home6>0</Home6>
<Away6>0</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>1</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1663</Ctr>
<Week>10</Week>
<Flight>1</Flight>
<Home1>7</Home1>
<Away1>9</Away1>
<Home2>10</Home2>
<Away2>11</Away2>
<Home3>8</Home3>
<Away3>12</Away3>
<Home4>1</Home4>
<Away4>4</Away4>
<Home5>2</Home5>
<Away5>6</Away5>
<Home6>3</Home6>
<Away6>5</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>0</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1664</Ctr>
<Week>11</Week>
<Flight>1</Flight>
<Home1>8</Home1>
<Away1>10</Away1>
<Home2>4</Home2>
<Away2>9</Away2>
<Home3>7</Home3>
<Away3>12</Away3>
<Home4>3</Home4>
<Away4>6</Away4>
<Home5>1</Home5>
<Away5>5</Away5>
<Home6>2</Home6>
<Away6>11</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>1</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1665</Ctr>
<Week>12</Week>
<Flight>1</Flight>
<Home1>3</Home1>
<Away1>12</Away1>
<Home2>5</Home2>
<Away2>8</Away2>
<Home3>1</Home3>
<Away3>6</Away3>
<Home4>2</Home4>
<Away4>9</Away4>
<Home5>7</Home5>
<Away5>10</Away5>
<Home6>4</Home6>
<Away6>11</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>0</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1666</Ctr>
<Week>13</Week>
<Flight>1</Flight>
<Home1>9</Home1>
<Away1>11</Away1>
<Home2>6</Home2>
<Away2>8</Away2>
<Home3>2</Home3>
<Away3>4</Away3>
<Home4>5</Home4>
<Away4>7</Away4>
<Home5>1</Home5>
<Away5>3</Away5>
<Home6>10</Home6>
<Away6>12</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>1</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1667</Ctr>
<Week>14</Week>
<Flight>1</Flight>
<Home1>0</Home1>
<Away1>0</Away1>
<Home2>0</Home2>
<Away2>0</Away2>
<Home3>0</Home3>
<Away3>0</Away3>
<Home4>0</Home4>
<Away4>0</Away4>
<Home5>0</Home5>
<Away5>0</Away5>
<Home6>0</Home6>
<Away6>0</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>0</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1668</Ctr>
<Week>15</Week>
<Flight>1</Flight>
<Home1>6</Home1>
<Away1>10</Away1>
<Home2>2</Home2>
<Away2>5</Away2>
<Home3>1</Home3>
<Away3>11</Away3>
<Home4>4</Home4>
<Away4>12</Away4>
<Home5>3</Home5>
<Away5>7</Away5>
<Home6>8</Home6>
<Away6>9</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>0</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1669</Ctr>
<Week>16</Week>
<Flight>1</Flight>
<Home1>0</Home1>
<Away1>0</Away1>
<Home2>0</Home2>
<Away2>0</Away2>
<Home3>0</Home3>
<Away3>0</Away3>
<Home4>0</Home4>
<Away4>0</Away4>
<Home5>0</Home5>
<Away5>0</Away5>
<Home6>0</Home6>
<Away6>0</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>1</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1670</Ctr>
<Week>17</Week>
<Flight>1</Flight>
<Home1>0</Home1>
<Away1>0</Away1>
<Home2>0</Home2>
<Away2>0</Away2>
<Home3>0</Home3>
<Away3>0</Away3>
<Home4>0</Home4>
<Away4>0</Away4>
<Home5>0</Home5>
<Away5>0</Away5>
<Home6>0</Home6>
<Away6>0</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>0</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1671</Ctr>
<Week>18</Week>
<Flight>1</Flight>
<Home1>0</Home1>
<Away1>0</Away1>
<Home2>0</Home2>
<Away2>0</Away2>
<Home3>0</Home3>
<Away3>0</Away3>
<Home4>0</Home4>
<Away4>0</Away4>
<Home5>0</Home5>
<Away5>0</Away5>
<Home6>0</Home6>
<Away6>0</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>1</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1672</Ctr>
<Week>19</Week>
<Flight>1</Flight>
<Home1>0</Home1>
<Away1>0</Away1>
<Home2>0</Home2>
<Away2>0</Away2>
<Home3>0</Home3>
<Away3>0</Away3>
<Home4>0</Home4>
<Away4>0</Away4>
<Home5>0</Home5>
<Away5>0</Away5>
<Home6>0</Home6>
<Away6>0</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>0</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1673</Ctr>
<Week>20</Week>
<Flight>1</Flight>
<Home1>0</Home1>
<Away1>0</Away1>
<Home2>0</Home2>
<Away2>0</Away2>
<Home3>0</Home3>
<Away3>0</Away3>
<Home4>0</Home4>
<Away4>0</Away4>
<Home5>0</Home5>
<Away5>0</Away5>
<Home6>0</Home6>
<Away6>0</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>1</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1674</Ctr>
<Week>1</Week>
<Flight>2</Flight>
<Home1>0</Home1>
<Away1>0</Away1>
<Home2>0</Home2>
<Away2>0</Away2>
<Home3>0</Home3>
<Away3>0</Away3>
<Home4>0</Home4>
<Away4>0</Away4>
<Home5>0</Home5>
<Away5>0</Away5>
<Home6>0</Home6>
<Away6>0</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>1</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1675</Ctr>
<Week>2</Week>
<Flight>2</Flight>
<Home1>3</Home1>
<Away1>10</Away1>
<Home2>4</Home2>
<Away2>8</Away2>
<Home3>1</Home3>
<Away3>9</Away3>
<Home4>5</Home4>
<Away4>11</Away4>
<Home5>2</Home5>
<Away5>12</Away5>
<Home6>6</Home6>
<Away6>7</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>0</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1676</Ctr>
<Week>3</Week>
<Flight>2</Flight>
<Home1>2</Home1>
<Away1>3</Away1>
<Home2>1</Home2>
<Away2>10</Away2>
<Home3>5</Home3>
<Away3>9</Away3>
<Home4>6</Home4>
<Away4>12</Away4>
<Home5>8</Home5>
<Away5>11</Away5>
<Home6>4</Home6>
<Away6>7</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
<Home8>0</Home8>
<Away8>0</Away8>
<Home9>0</Home9>
<Away9>0</Away9>
<Back9>1</Back9>
</ScheduleMaster>
<ScheduleMaster>
<Ctr>1677</Ctr>
<Week>4</Week>
<Flight>2</Flight>
<Home1>9</Home1>
<Away1>10</Away1>
<Home2>3</Home2>
<Away2>4</Away2>
<Home3>5</Home3>
<Away3>6</Away3>
<Home4>7</Home4>
<Away4>8</Away4>
<Home5>11</Home5>
<Away5>12</Away5>
<Home6>1</Home6>
<Away6>2</Away6>
<Home7>0</Home7>
<Away7>0</Away7>
