=== QuiWorks/golf-league/src/test/resources/legacy/schema/Tees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="TeesList">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Tees" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Tees">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="Tees Back9 " primary="yes" unique="yes" clustered="no" order="asc asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="4Q6N/8duZUOWIhB079+QMg==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Tees" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="CourseRating" minOccurs="0" od:jetType="single" od:sqlSType="real" type="xsd:float">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1695"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="2"/>
<od:fieldProperty name="Caption" type="12" value="Course Rating"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Slope" minOccurs="0" od:jetType="single" od:sqlSType="real" type="xsd:float">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="2"/>
<od:fieldProperty name="Caption" type="12" value="Slope"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Back9" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== QuiWorks/golf-league/src/test/resources/legacy/data/Tees.xml
<?xml version="1.0" encoding="UTF-8"?>
<TeesList xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Tees.xsd" generated="2021-06-08T17:54:32">
<Tees>
<Tees>_</Tees>
<CourseRating>0</CourseRating>
<Slope>0</Slope>
<Back9>0</Back9>
</Tees>
<Tees>
<Tees>Black</Tees>
<CourseRating>36</CourseRating>
<Slope>135</Slope>
<Back9>1</Back9>
</Tees>
<Tees>
<Tees>Black</Tees>
<CourseRating>35.5</CourseRating>
<Slope>129</Slope>
<Back9>0</Back9>
</Tees>
<Tees>
<Tees>Blue</Tees>
<CourseRating>34.9</CourseRating>
<Slope>130</Slope>
<Back9>1</Back9>
</Tees>
<Tees>
<Tees>Blue</Tees>
<CourseRating>34.3</CourseRating>
<Slope>124</Slope>
<Back9>0</Back9>
</Tees>
<Tees>
<Tees>Gold</Tees>
<CourseRating>35</CourseRating>
<Slope>123</Slope>
<Back9>1</Back9>
</Tees>
<Tees>
<Tees>Gold</Tees>
<CourseRating>35</CourseRating>
<Slope>122</Slope>
<Back9>0</Back9>
</Tees>
<Tees>
<Tees>Silver</Tees>
<CourseRating>37</CourseRating>
<Slope>139</Slope>
<Back9>1</Back9>
</Tees>
<Tees>
<Tees>Silver</Tees>
<CourseRating>36.8</CourseRating>
<Slope>130</Slope>
<Back9>0</Back9>
</Tees>
</TeesList>
