=== QuiWorks/golf-league/src/test/resources/legacy/schema/TeeTimes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="TeeTimesList">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="TeeTimes" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="TeeTimes">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Flight" index-key="Flight Slot " primary="no" unique="yes" clustered="no" order="asc asc"/>
<od:index index-name="PrimaryKey" index-key="Ctr " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="aw2UkvgWUEursocjPe+hrQ==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="OrderBy" type="12" value="TeeTimes.Flight, TeeTimes.Slot"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Ctr" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Flight" minOccurs="0" od:jetType="byte" od:sqlSType="tinyint" type="xsd:unsignedByte">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Slot" minOccurs="0" od:jetType="byte" od:sqlSType="tinyint" type="xsd:unsignedByte">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="TeeTime" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="10"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== QuiWorks/golf-league/src/test/resources/legacy/data/TeeTimes.xml
<?xml version="1.0" encoding="UTF-8"?>
<TeeTimesList xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="TeeTimes.xsd" generated="2021-06-05T13:54:40">
    <TeeTimes>
        <Ctr>13</Ctr>
        <Flight>1</Flight>
        <Slot>1</Slot>
        <TeeTime>4:30</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>14</Ctr>
        <Flight>1</Flight>
        <Slot>2</Slot>
        <TeeTime>4:38</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>15</Ctr>
        <Flight>1</Flight>
        <Slot>3</Slot>
        <TeeTime>4:46</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>16</Ctr>
        <Flight>1</Flight>
        <Slot>4</Slot>
        <TeeTime>4:54</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>17</Ctr>
        <Flight>1</Flight>
        <Slot>5</Slot>
        <TeeTime>5:02</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>18</Ctr>
        <Flight>1</Flight>
        <Slot>6</Slot>
        <TeeTime>5:10</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>19</Ctr>
        <Flight>3</Flight>
        <Slot>1</Slot>
        <TeeTime>4:30</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>20</Ctr>
        <Flight>3</Flight>
        <Slot>2</Slot>
        <TeeTime>4:38</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>21</Ctr>
        <Flight>3</Flight>
        <Slot>3</Slot>
        <TeeTime>4:46</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>22</Ctr>
        <Flight>3</Flight>
        <Slot>4</Slot>
        <TeeTime>4:54</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>24</Ctr>
        <Flight>3</Flight>
        <Slot>6</Slot>
        <TeeTime>5:10</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>37</Ctr>
        <Flight>2</Flight>
        <Slot>3</Slot>
        <TeeTime>5:34</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>38</Ctr>
        <Flight>2</Flight>
        <Slot>4</Slot>
        <TeeTime>5:42</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>39</Ctr>
        <Flight>2</Flight>
        <Slot>5</Slot>
        <TeeTime>5:50</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>40</Ctr>
        <Flight>2</Flight>
        <Slot>6</Slot>
        <TeeTime>5:58</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>43</Ctr>
        <Flight>4</Flight>
        <Slot>3</Slot>
        <TeeTime>5:34</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>44</Ctr>
        <Flight>4</Flight>
        <Slot>4</Slot>
        <TeeTime>5:42</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>45</Ctr>
        <Flight>4</Flight>
        <Slot>5</Slot>
        <TeeTime>5:50</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>46</Ctr>
        <Flight>4</Flight>
        <Slot>6</Slot>
        <TeeTime>5:58</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>53</Ctr>
        <Flight>3</Flight>
        <Slot>5</Slot>
        <TeeTime>5:02</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>56</Ctr>
        <Flight>2</Flight>
        <Slot>1</Slot>
        <TeeTime>5:18</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>57</Ctr>
        <Flight>2</Flight>
        <Slot>2</Slot>
        <TeeTime>5:26</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>60</Ctr>
        <Flight>4</Flight>
        <Slot>1</Slot>
        <TeeTime>5:18</TeeTime>
    </TeeTimes>
    <TeeTimes>
        <Ctr>61</Ctr>
        <Flight>4</Flight>
        <Slot>2</Slot>
        <TeeTime>5:26</TeeTime>
    </TeeTimes>
</TeeTimesList>
