=== QuiWorks/golf-league/src/test/resources/legacy/schema/WeekDates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="WeekDatesList">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="WeekDates" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="WeekDates">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="Week " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="WeekBucket" index-key="WeekBucket " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="WeekDate" index-key="WeekDate " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="WeekDate1" index-key="Dateplayed " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="RbTUcaGu5EiewQHXQWL6Qw==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="OrderBy" type="12" value="[WeekDates].[Week], [WeekDates].[WeekDate]"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Week" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="WeekDate" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2130"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowDatePicker" type="3" value="1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="EventType" minOccurs="0" od:jetType="byte" od:sqlSType="tinyint" type="xsd:unsignedByte">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Back9" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Status" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Tees" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Back9Spcl" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="WeekBucket" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Shotgun" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="Caption" type="12" value="Shotgun"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Rebuild" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="Caption" type="12" value="Rebuild"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Dateplayed" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Caption" type="12" value="Date Played"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowDatePicker" type="3" value="1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== QuiWorks/golf-league/src/test/resources/legacy/data/WeekDates.xml
<?xml version="1.0" encoding="UTF-8"?>
<WeekDatesList xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="WeekDates.xsd" generated="2021-06-05T13:55:58">
<WeekDates>
<Week>1</Week>
<WeekDate>2009-05-06T00:00:00</WeekDate>
<EventType>23</EventType>
<Back9>1</Back9>
<Status>1</Status>
<Tees>Black</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>0</WeekBucket>
<Shotgun>0</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-05-06T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>2</Week>
<WeekDate>2009-05-13T00:00:00</WeekDate>
<EventType>1</EventType>
<Back9>0</Back9>
<Status>1</Status>
<Tees>Blue</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>1</WeekBucket>
<Shotgun>1</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-05-13T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>3</Week>
<WeekDate>2009-05-20T00:00:00</WeekDate>
<EventType>1</EventType>
<Back9>1</Back9>
<Status>1</Status>
<Tees>Black</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>2</WeekBucket>
<Shotgun>1</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-05-20T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>4</Week>
<WeekDate>2009-05-27T00:00:00</WeekDate>
<EventType>1</EventType>
<Back9>0</Back9>
<Status>1</Status>
<Tees>Black</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>3</WeekBucket>
<Shotgun>1</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-05-27T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>5</Week>
<WeekDate>2009-06-03T00:00:00</WeekDate>
<EventType>4</EventType>
<Back9>1</Back9>
<Status>1</Status>
<Tees>_</Tees>
<Back9Spcl>1</Back9Spcl>
<WeekBucket>0</WeekBucket>
<Shotgun>0</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-06-03T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>6</Week>
<WeekDate>2009-06-10T00:00:00</WeekDate>
<EventType>1</EventType>
<Back9>1</Back9>
<Status>1</Status>
<Tees>Blue</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>4</WeekBucket>
<Shotgun>1</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-06-10T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>7</Week>
<WeekDate>2009-06-17T00:00:00</WeekDate>
<EventType>1</EventType>
<Back9>0</Back9>
<Status>1</Status>
<Tees>Black</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>5</WeekBucket>
<Shotgun>1</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-06-17T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>8</Week>
<WeekDate>2009-06-24T00:00:00</WeekDate>
<EventType>1</EventType>
<Back9>1</Back9>
<Status>1</Status>
<Tees>Black</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>6</WeekBucket>
<Shotgun>1</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-06-24T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>9</Week>
<WeekDate>2009-07-01T00:00:00</WeekDate>
<EventType>81</EventType>
<Back9>1</Back9>
<Status>1</Status>
<Tees>Blue</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>0</WeekBucket>
<Shotgun>1</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-07-01T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>10</Week>
<WeekDate>2009-07-08T00:00:00</WeekDate>
<EventType>1</EventType>
<Back9>0</Back9>
<Status>1</Status>
<Tees>Blue</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>7</WeekBucket>
<Shotgun>1</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-07-08T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>11</Week>
<WeekDate>2009-07-15T00:00:00</WeekDate>
<EventType>1</EventType>
<Back9>1</Back9>
<Status>1</Status>
<Tees>Black</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>8</WeekBucket>
<Shotgun>1</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-07-15T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>12</Week>
<WeekDate>2009-07-22T00:00:00</WeekDate>
<EventType>1</EventType>
<Back9>0</Back9>
<Status>1</Status>
<Tees>Black</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>9</WeekBucket>
<Shotgun>1</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-07-22T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>13</Week>
<WeekDate>2009-07-29T00:00:00</WeekDate>
<EventType>1</EventType>
<Back9>1</Back9>
<Status>1</Status>
<Tees>Blue</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>10</WeekBucket>
<Shotgun>1</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-07-29T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>14</Week>
<WeekDate>2009-08-05T00:00:00</WeekDate>
<EventType>78</EventType>
<Back9>0</Back9>
<Status>1</Status>
<Tees>_</Tees>
<Back9Spcl>1</Back9Spcl>
<WeekBucket>0</WeekBucket>
<Shotgun>1</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-08-05T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>15</Week>
<WeekDate>2009-08-12T00:00:00</WeekDate>
<EventType>1</EventType>
<Back9>0</Back9>
<Status>0</Status>
<Tees>Black</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>11</WeekBucket>
<Shotgun>1</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-08-12T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>16</Week>
<WeekDate>2009-08-19T00:00:00</WeekDate>
<EventType>27</EventType>
<Back9>1</Back9>
<Status>0</Status>
<Tees>Black</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>0</WeekBucket>
<Shotgun>1</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-08-19T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>17</Week>
<WeekDate>2009-08-26T00:00:00</WeekDate>
<EventType>21</EventType>
<Back9>0</Back9>
<Status>0</Status>
<Tees>Black</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>0</WeekBucket>
<Shotgun>0</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-08-26T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>18</Week>
<WeekDate>2009-09-02T00:00:00</WeekDate>
<EventType>21</EventType>
<Back9>1</Back9>
<Status>0</Status>
<Tees>Black</Tees>
<Back9Spcl>1</Back9Spcl>
<WeekBucket>0</WeekBucket>
<Shotgun>0</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-09-02T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>19</Week>
<WeekDate>2009-09-09T00:00:00</WeekDate>
<EventType>21</EventType>
<Back9>0</Back9>
<Status>0</Status>
<Tees>Black</Tees>
<Back9Spcl>0</Back9Spcl>
<WeekBucket>0</WeekBucket>
<Shotgun>0</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-09-09T00:00:00</Dateplayed>
</WeekDates>
<WeekDates>
<Week>20</Week>
<WeekDate>2009-09-16T00:00:00</WeekDate>
<EventType>21</EventType>
<Back9>1</Back9>
<Status>0</Status>
<Tees>Black</Tees>
<Back9Spcl>1</Back9Spcl>
<WeekBucket>0</WeekBucket>
<Shotgun>0</Shotgun>
<Rebuild>0</Rebuild>
<Dateplayed>2009-09-16T00:00:00</Dateplayed>
</WeekDates>
</WeekDatesList>
